### ISSUE TITLE
Need an additional field for sending files like apk

### ISSUE THREAD

**Issue by JeromeCHA** [monolithic-adam/bitrise-step-chatwork-message#1]
In Android team, we are using the environment variable `$BITRISE_PUBLIC_INSTALL_PAGE_URL` created by the Gradle step to send our apk. Do you think it is possible to add an additional field for this please? 🙏

**Comment by monolithic-adam** [comment]
Will work on it this weekend!

**Comment by monolithic-adam** [comment]
#2 fixed in version 0.0.2 as an install page url! 👍
